# Generated by Django 5.2.1 on 2025-05-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment'), ('activity', 'Activity'), ('tour', 'Tour'), ('car', 'Car'), ('other', 'Other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('bookable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.bookable')),
            ],
        ),
        migrations.AddField(
            model_name='bookable',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel.destination'),
        ),
    ]
