# Generated by Django 5.2.1 on 2025-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('slide_img', models.JSONField(default=list)),
                ('type', models.CharField(max_length=50)),
                ('ratings', models.CharField(max_length=10)),
                ('number_of_reviews', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=10)),
                ('luggage', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=50)),
                ('delay_animation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('properties', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('hover_text', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('travellers', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_properties', models.CharField(blank=True, max_length=20, null=True)),
                ('col_class', models.CharField(blank=True, max_length=50, null=True)),
                ('delay_animation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(max_length=255)),
                ('slide_img', models.JSONField(default=list)),
                ('ratings', models.CharField(max_length=10)),
                ('number_of_reviews', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('delay_animation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('slide_img', models.JSONField(default=list)),
                ('ratings', models.CharField(max_length=10)),
                ('number_of_reviews', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('guest', models.CharField(max_length=10)),
                ('bedroom', models.CharField(max_length=10)),
                ('bed', models.CharField(max_length=10)),
                ('delay_animation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('slide_img', models.JSONField(default=list)),
                ('duration', models.CharField(max_length=10)),
                ('number_of_reviews', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('tour_type', models.CharField(max_length=50)),
                ('delay_animation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('tour_number', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('delay_animation', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tour Categories',
            },
        ),
    ]
